// Pure helpers for the "Submit to store" action (Google Play + iOS App Store). We follow
// "scaffold CI, manual submit": generate the CI config + a checklist of the manual Console
// steps; the actual build+upload runs on the user's own CI (GitHub Actions for Play, the
// managed Codemagic mac for iOS) with their secrets, and production release stays manual.
// Modeled on the PROVEN apkipa pipeline (/srv/apkipa/my_counter_app: play-release.yml +
// codemagic.yaml). No I/O here — unit-tested.

export const STORES = ['play', 'ios'];
export const PLAY_TRACKS = ['internal', 'alpha', 'beta', 'production'];
export function normalizeTrack(t) { return PLAY_TRACKS.includes(String(t)) ? String(t) : 'internal'; }

export const PLAY_WORKFLOW_PATH = '.github/workflows/play-release.yml';
export const IOS_WORKFLOW_PATH = 'codemagic.yaml';
export function submissionDoc(store) { return store === 'ios' ? 'SUBMISSION-IOS.md' : 'SUBMISSION-PLAY.md'; }

// A safe default bundle/application id when the user hasn't supplied one (they MUST set a
// real reverse-DNS id before a real submission — the checklist says so).
export function defaultBundleId(project) {
  const s = String(project || 'app').toLowerCase().replace(/[^a-z0-9]/g, '').slice(0, 30) || 'app';
  return `com.example.${s}`;
}
const BUNDLE_RE = /^[A-Za-z][A-Za-z0-9_]*(\.[A-Za-z][A-Za-z0-9_]*)+$/;
export function validBundleId(s) { return BUNDLE_RE.test(String(s || '')); }

// ---- Google Play (GitHub Actions, mirrors apkipa/play-release.yml) ----------
// Monotonic versionCode (run_number + 10) — Play rejects duplicate/decreasing codes;
// analyze+test gates; signs with the UPLOAD key from secrets (Play re-signs); track/status
// configurable. packageName comes from a repo VARIABLE so the workflow stays generic.
export function playWorkflowYaml({ track = 'internal', status = 'completed' } = {}) {
  const t = normalizeTrack(track);
  const st = ['completed', 'draft', 'inProgress', 'halted'].includes(String(status)) ? String(status) : 'completed';
  return `# Generated by webtmux — build a signed AAB and upload to Google Play (${t} track).
# Manual trigger (or push a vX.Y.Z tag). Requires the repo secrets + variable in ${submissionDoc('play')}.
name: Play Release (AAB -> ${t})
on:
  workflow_dispatch:
  push:
    tags: [ 'v*' ]
concurrency:
  group: play-release
  cancel-in-progress: false
jobs:
  release-aab:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.44.4
          channel: stable
          cache: true
      - run: flutter pub get
      - run: flutter analyze
      - run: flutter test
      - name: Decode upload keystore
        run: echo "\${{ secrets.ANDROID_KEYSTORE_BASE64 }}" | base64 -d > android/app/upload-keystore.jks
      - name: Write key.properties
        run: |
          cat > android/key.properties <<EOF
          storeFile=upload-keystore.jks
          storePassword=\${{ secrets.ANDROID_STORE_PASSWORD }}
          keyPassword=\${{ secrets.ANDROID_KEY_PASSWORD }}
          keyAlias=\${{ secrets.ANDROID_KEY_ALIAS }}
          EOF
      - name: Compute version
        id: ver
        run: |
          echo "code=\$(( \${{ github.run_number }} + 10 ))" >> "\$GITHUB_OUTPUT"
          if [[ "\${GITHUB_REF}" == refs/tags/v* ]]; then echo "name=\${GITHUB_REF##*/v}" >> "\$GITHUB_OUTPUT"; else echo "name=" >> "\$GITHUB_OUTPUT"; fi
      - name: Build release AAB
        run: |
          ARGS="--release --build-number=\${{ steps.ver.outputs.code }}"
          if [ -n "\${{ steps.ver.outputs.name }}" ]; then ARGS="\$ARGS --build-name=\${{ steps.ver.outputs.name }}"; fi
          flutter build appbundle \$ARGS
      - name: Upload to Google Play (${t})
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: \${{ secrets.PLAY_SERVICE_ACCOUNT_JSON }}
          packageName: \${{ vars.PLAY_PACKAGE_NAME }}
          releaseFiles: build/app/outputs/bundle/release/app-release.aab
          track: ${t}
          status: ${st}
      - uses: actions/upload-artifact@v4
        with:
          name: release-aab
          path: build/app/outputs/bundle/release/app-release.aab
          if-no-files-found: error
`;
}

// ---- iOS App Store (Codemagic, mirrors apkipa/codemagic.yaml) ----------------
// Managed App Store Connect signing via a named integration — no manual certs/profiles.
export function codemagicYaml({ bundleId, integration = 'CodemagicAppStoreKey' } = {}) {
  const bid = validBundleId(bundleId) ? bundleId : 'com.example.app';
  const integ = String(integration || 'CodemagicAppStoreKey').replace(/[^A-Za-z0-9_-]/g, '') || 'CodemagicAppStoreKey';
  return `# Generated by webtmux — signed iOS build to TestFlight via Codemagic (cloud macOS).
# Managed signing: the App Store Connect integration named \`${integ}\` lets Codemagic fetch
# (and create if missing) the distribution cert + provisioning profile. See ${submissionDoc('ios')}.
workflows:
  ios-release:
    name: iOS Release Build (TestFlight)
    instance_type: mac_mini_m2
    max_build_duration: 60
    integrations:
      app_store_connect: ${integ}
    triggering:
      events: [ push ]
      branch_patterns:
        - pattern: main
          include: true
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      ios_signing:
        distribution_type: app_store
        bundle_identifier: ${bid}
    scripts:
      - name: Get Flutter packages
        script: flutter pub get
      - name: Install CocoaPods
        script: find . -name "Podfile" -execdir pod install \\;
      - name: Apply managed signing profiles
        script: xcode-project use-profiles
      - name: Build signed .ipa
        script: flutter build ipa --release
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
`;
}

export function playChecklistMd({ project = 'app', track = 'internal' } = {}) {
  const t = normalizeTrack(track);
  const trackName = t === 'internal' ? 'Internal testing' : t;
  return `# Google Play submission — ${project}

\`${PLAY_WORKFLOW_PATH}\` builds a signed AAB and uploads it to the **${t}** track on YOUR GitHub
Actions — that's the programmatic path. But the Play API **can't create the app or do the very
first upload**, so do these once by hand; after that it's automatic.

## 1. Create the app + the FIRST .aab upload (manual — the Play API can't do this)
1. [play.google.com/console](https://play.google.com/console) → **Create app** (name, default
   language, App/**Game**, **Free**) → accept declarations. ⚠️ The **package name is permanent and
   globally unique** the moment the first AAB lands — make sure it's right (it's your \`applicationId\`).
2. Enable **Play App Signing** (let Google generate the app signing key; your keystore is the
   *upload* key — nothing to paste).
3. **Get a first AAB:** run the **"Play Release"** Action once — it builds the AAB and attaches it as
   the **\`release-aab\`** artifact (download it from the workflow run). *(The API upload step will
   fail until this manual upload exists — expected for a brand-new app.)*
4. **Upload it:** *Test and release → Testing → ${trackName} → Create new release → upload the .aab →
   Save → Review → Start rollout.*

## 2. Service-account JSON — how to get it (one time)
1. **Google Cloud Console** (same Google account) → **IAM & Admin → Service Accounts → Create
   service account** (name e.g. \`play-ci\`); finish (no roles needed here).
2. Open that service account → **Keys → Add key → Create new key → JSON** → a \`.json\` downloads.
   **That file is the credential.**
3. **Enable the API:** APIs & Services → enable **"Google Play Android Developer API"** for the project.
4. **Grant it in Play Console:** *Users and permissions → Invite new users* → paste the SA email
   (\`…@….iam.gserviceaccount.com\`) → grant **Admin (release)** for this app → send.

## 3. Credentials (auto-wired — usually nothing to do here)
When you click **Submit to Play**, webtmux generates a stable upload keystore and **sets the GitHub
Actions secrets for you** via \`gh\`: \`PLAY_SERVICE_ACCOUNT_JSON\` (from your saved Google Play
credential), \`ANDROID_KEYSTORE_BASE64\` + \`ANDROID_STORE_PASSWORD\` + \`ANDROID_KEY_PASSWORD\` +
\`ANDROID_KEY_ALIAS\`, and the \`PLAY_PACKAGE_NAME\` variable. You normally don't open GitHub settings.
- If the Submit result lists a secret as **failed**, your GitHub token lacks **Secrets** write —
  use a classic PAT with \`repo\` scope (or a fine-grained token with Secrets: read/write), then
  re-Submit; or set them by hand under *Settings → Secrets and variables → Actions*.
- Ensure \`PLAY_PACKAGE_NAME\` matches your app's \`applicationId\` and the Play Console listing.

## 4. From now on it's programmatic
Actions → **"Play Release"** → Run workflow (or push a \`vX.Y.Z\` tag). versionCode auto-increments
(\`run_number + 10\`) so uploads never collide; it builds + uploads the AAB to the **${t}** track via API.

## 5. Go live (manual gate)
**\`internal\`** is instant (no review) — best for test installs, but does **not** count toward the
production gate. Production needs a **closed (\`alpha\`)** test with **≥12 testers opted in for 14
continuous days**; an unpublished app's first closed release uploads as \`status: draft\` (roll it out
by hand → submits for review). Then promote to production.

## Store listing assets (auto-generated)
- **Screenshots** + a **1024×500 feature graphic** are generated into \`store-assets/\` each build —
  upload them in the listing. You still add a **512×512 app icon** + the store copy (title /
  short + full description / category).
`;
}

export function iosChecklistMd({ project = 'app', bundleId = 'com.example.app', integration = 'CodemagicAppStoreKey' } = {}) {
  return `# iOS App Store submission — ${project}

\`${IOS_WORKFLOW_PATH}\` builds a signed \`.ipa\` on Codemagic's cloud macOS and submits it to
**TestFlight**. iOS needs a paid Apple Developer Program ($99/yr) and a Codemagic account.

## 1. Apple (one time)
- Enroll in the **Apple Developer Program**.
- Register the **bundle identifier** \`${bundleId}\` (App Store Connect → Identifiers, or it's
  created during App creation). It MUST match \`ios_signing.bundle_identifier\` in \`${IOS_WORKFLOW_PATH}\`,
  your Xcode project, and (if you use Firebase) the Firebase iOS app.
- Create an **App Store Connect API key** (Users and Access → Integrations → Keys, role App
  Manager): download the **\`.p8\`** once; record the **Issuer ID** + **Key ID**.
- App Store Connect → **My Apps → (+) New App** → iOS → pick the bundle id → globally-unique name.

## 2. Codemagic (one time)
- Create a (personal, free-tier) Codemagic account; connect this GitHub repo.
- Teams/Personal → Integrations → **App Store Connect** → add the API key (Issuer ID + Key ID +
  the \`.p8\`) and **name the integration exactly \`${integration}\`** (the yaml references it by name).

## 3. Firebase on iOS (only if the app uses Firebase)
- Run \`flutterfire configure\` and include **iOS** with bundle id \`${bundleId}\`, or the app
  **crashes on launch** (\`DefaultFirebaseOptions.currentPlatform\` throws with no iOS block).

## 4. Build
- Push to \`main\` (the workflow triggers on it) or trigger a build in Codemagic. On success the
  build lands in **TestFlight**; the \`.ipa\` is in the Artifacts tab. Promote to the App Store
  manually once it passes review.

## Screenshots
- webtmux auto-generates **iPhone 6.5″ + iPad 13″** screenshots in \`store-assets/\` during each
  build — upload those in App Store Connect (re-run the build to refresh them).

> Secrets stay in Codemagic / Apple — never commit the \`.p8\` (it's gitignored).
`;
}
